"""Privacy-safe intelligent suggester agent for 1405 Cultural Reporting.

Analyzes indexed messages and candidates to produce structured recommendations
for the human reviewer, including:
- Recommended workbook program kind
- Ashura Pilgrimage distinct classification (Rule C12)
- Official presence detection for Honor/Customer Care (Rule B9/C8)
- Unit scope and courthouse location extraction
- Pre-fill hints for star cells (reception, announcement, speaker, gifts)

In accordance with ADR-42, ADR-46 and ADR-51:
- Never auto-commits an event without human review.
- Suggestion is an assist to central staff.
- Strict privacy: No PII, phones or tokens leaked in suggestion records.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import re
from typing import Any, Mapping, Sequence

from .model import ProgramId, ProgramKind, UnitScope


@dataclass(slots=True)
class AgentSuggestion:
    """Structured proposal generated by the agent for a reporting candidate."""

    candidate_id: str
    recommended_program: str
    confidence: float
    reasoning: str
    extracted_attendees: int | None = None
    extracted_unit_scope: str = "provincial_hq"
    extracted_unit_name: str = ""
    official_present_suggested: bool | None = None
    is_ashura_pilgrimage: bool = False
    star_field_hints: dict[str, Any] = field(default_factory=dict)
    rule_version: str = "1.0"
    rule_name: str = "general"
    provenance: dict[str, Any] = field(default_factory=dict)
    is_abstain: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "recommended_program": self.recommended_program,
            "confidence": round(self.confidence, 2),
            "reasoning": self.reasoning,
            "extracted_attendees": self.extracted_attendees,
            "extracted_unit_scope": self.extracted_unit_scope,
            "extracted_unit_name": self.extracted_unit_name,
            "official_present_suggested": self.official_present_suggested,
            "is_ashura_pilgrimage": self.is_ashura_pilgrimage,
            "star_field_hints": self.star_field_hints,
            "rule_version": self.rule_version,
            "rule_name": self.rule_name,
            "provenance": self.provenance,
            "is_abstain": self.is_abstain,
        }


# High-ranking official keywords in judiciary context
_CHIEF_JUSTICE_PATTERNS = re.compile(
    r"(?:رئیس[‌ ]?کل(?:\s+محترم)?\s+دادگستری|رئیس\s+کل\s+استان|مقام\s+ارشد\s+قضایی|حجت[‌ ]?الاسلام\s+والمسلمین\s+اکبری|دکتر\s+اکبری|ریاست\s+محترم\s+کل)",
    re.UNICODE,
)

# Ashura pilgrimage indicators
_ASHURA_PATTERNS = re.compile(
    r"(?:زیارت\s+عاشورا|قرائت\s+زیارت\s+عاشورا|دعای\s+عاشورا|مراسم\s+پرفیض\s+زیارت\s+عاشورا)",
    re.UNICODE,
)

# Known regional courthouses in Mazandaran
_MAZANDARAN_CITIES = (
    "ساری", "بابل", "آمل", "قائمشهر", "قائم‌شهر", "تنکابن", "چالوس",
    "نوشهر", "نکا", "بهشهر", "رامسر", "بابلسر", "محمودآباد", "سوادکوه",
    "جویبار", "فریدونکنار", "فریدون‌کنار", "گلوگاه", "میاندرود", "میاندورود",
    "کلاردشت", "سیمرغ", "عباس‌آباد", "زیراب", "پل‌سفید", "چمستان", "دابودشت",
)

_ATTENDEES_REGEX = re.compile(r"([۰-۹0-9]{1,6})\s*(?:نفر|شخص|شرکت[‌ ]?کننده|مدعو|همکار)")


def _to_int(digit_str: str) -> int | None:
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    ascii_digits = "0123456789"
    trans = str.maketrans(persian_digits, ascii_digits)
    try:
        return int(digit_str.translate(trans))
    except (ValueError, TypeError):
        return None


class ReportingSuggester:
    """Agent assistant that generates suggestions for reporting candidates."""

    RULE_VERSION = "1.0"

    def analyze(
        self,
        candidate_id: str,
        text: str,
        matched_programs: Sequence[str] = (),
        existing_attendees: int | None = None,
        dialog_label: str = "",
        scoped_aliases: Sequence[Mapping[str, Any]] = (),
    ) -> AgentSuggestion:
        content = text or ""
        dialog = dialog_label or ""
        combined = f"{dialog}\n{content}"

        reasons: list[str] = []
        star_hints: dict[str, Any] = {}
        rule_name = "general"
        is_abstain = False

        # 0. Check scoped aliases first (ADR-42, ADR-46, Strategy §7).
        # Scope gate (Strategy §9.5): a scoped alias must not leak into an
        # unrelated context — global applies everywhere, local only to its
        # own candidate, program only when the indexer matched that program,
        # and unit only when the target unit is evidenced in the message or
        # dialog label text.
        alias_matched = False
        matched_program_set = {str(p) for p in matched_programs}
        if scoped_aliases:
            for alias in scoped_aliases:
                if alias.get("status") != "active":
                    continue
                scope_kind = str(alias.get("scope_kind") or "global").strip()
                scope_target = str(alias.get("scope_target") or "").strip()
                if scope_kind == "local" and scope_target != candidate_id:
                    continue
                if scope_kind == "program" and scope_target not in matched_program_set:
                    continue
                if scope_kind == "unit" and (not scope_target or scope_target not in combined):
                    continue
                alias_word = str(alias.get("alias_text") or "").strip()
                if alias_word and alias_word in combined:
                    if alias.get("target_type") == "program":
                        recommended_prog = str(alias["canonical_target"])
                        confidence = min(0.95, float(alias.get("weight", 0.90)))
                        rule_name = "rule_scoped_alias"
                        reasons.append(f"انطباق با الیاس دامنه‌دار «{alias_word}» ({recommended_prog})")
                        alias_matched = True
                        break

        if not alias_matched:
            # 1. Check Ashura Pilgrimage
            is_ashura = bool(_ASHURA_PATTERNS.search(combined))
            if is_ashura:
                reasons.append("شناسایی قرائت زیارت عاشورا (موضوع بند C12 دستورالعمل)")
                recommended_prog = "ceremonies"
                confidence = 0.95
                rule_name = "rule_c12_ashura"
            # 2. Check Honor / Appreciation
            elif any(k in combined for k in ("تکریم", "تجلیل", "تقدیر از", "بازنشستگان", "کارمند نمونه")):
                recommended_prog = "honor"
                confidence = 0.88
                rule_name = "rule_keyword_honor"
                reasons.append("شناسایی کلیدواژه‌های تکریم و تجلیل")
            # 3. Check Prayer
            elif any(k in combined for k in ("نماز جماعت", "اقامه نماز", "جشن تکلیف", "نمازخانه", "ستاد اقامه نماز")):
                recommended_prog = "prayer"
                confidence = 0.90
                rule_name = "rule_keyword_prayer"
                reasons.append("شناسایی فعالیت‌های توسعه فرهنگ اقامه نماز")
            # 4. Check Contests
            elif any(k in combined for k in ("مسابقه", "مسابقات", "رقابت", "جشنواره فرهنگی", "کتابخوانی")):
                recommended_prog = "contest"
                confidence = 0.85
                rule_name = "rule_keyword_contest"
                reasons.append("شناسایی رویداد مسابقه/رقابت")
            # 5. Check Trip
            elif any(k in combined for k in ("اردو", "اردوی", "بازدید زیارتی", "کاروان")):
                recommended_prog = "trip"
                confidence = 0.88
                rule_name = "rule_keyword_trip"
                reasons.append("شناسایی اردوی فرهنگی یا زیارتی")
            # 6. Check Customer Care
            elif any(k in combined for k in ("ارباب رجوع", "تکریم مراجعین", "میز خدمت")):
                recommended_prog = "customer_care"
                confidence = 0.82
                rule_name = "rule_keyword_customer_care"
                reasons.append("شناسایی تشویق و تکریم ارباب رجوع")
            # 7. Check Charter
            elif any(k in combined for k in ("منشور اخلاقی", "منشور حقوق")):
                recommended_prog = "charter"
                confidence = 0.80
                rule_name = "rule_keyword_charter"
                reasons.append("شناسایی اقدامات منشور اخلاقی")
            # Fallback to matched programs or abstain on ambiguity (Strategy §7 & §9.5)
            else:
                if matched_programs:
                    recommended_prog = matched_programs[0]
                    confidence = 0.70
                    rule_name = "rule_indexer_match"
                    reasons.append(f"استفاده از دسته‌بندی اولیه ایندکسر ({recommended_prog})")
                else:
                    # Conservative Abstain: Do not guess or default to ceremonies without evidence!
                    recommended_prog = "unknown"
                    confidence = 0.0
                    rule_name = "rule_abstain"
                    is_abstain = True
                    reasons.append("متن فاقد کلیدواژه‌های قطعی برنامه‌هاست؛ دستیار از پیشنهاد خودکار خودداری می‌کند (Abstain)")
        else:
            is_ashura = bool(_ASHURA_PATTERNS.search(combined))

        # Official presence check
        official_present: bool | None = None
        if _CHIEF_JUSTICE_PATTERNS.search(combined):
            official_present = True
            reasons.append("حضور رئیس‌کل دادگستری استان در متن احراز شد (شرط B9/C8)")
            star_hints["official_present"] = True
        elif recommended_prog in ("honor", "customer_care"):
            official_present = False
            reasons.append("نام یا عنوان مقام ارشد استانی در متن یافت نشد (نیازمند تأیید دستی)")

        # Unit Scope & Courthouse Name extraction
        extracted_unit_scope = "provincial_hq"
        extracted_unit_name = ""

        if "شورای حل اختلاف" in combined:
            extracted_unit_scope = "special_council"
            extracted_unit_name = "شورای حل اختلاف"
        elif any(term in combined for term in ("حوزه قضایی", "دادگستری شهرستان", "دادسرای")):
            extracted_unit_scope = "courthouse"

        for city in _MAZANDARAN_CITIES:
            if city in combined:
                extracted_unit_name = f"دادگستری {city}"
                if extracted_unit_scope != "special_council":
                    extracted_unit_scope = "courthouse"
                reasons.append(f"محل یا حوزه قضایی «{city}» شناسایی شد")
                break

        if not extracted_unit_name:
            if "ستاد" in combined or "دادگستری کل" in combined:
                extracted_unit_name = "ستاد دادگستری کل استان"
                extracted_unit_scope = "provincial_hq"

        # Attendees count
        extracted_attendees = existing_attendees
        if extracted_attendees is None:
            match = _ATTENDEES_REGEX.search(combined)
            if match:
                extracted_attendees = _to_int(match.group(1))
                if extracted_attendees:
                    reasons.append(f"تعداد شرکت‌کنندگان: {extracted_attendees} نفر")

        # Star field hints
        if any(w in combined for w in ("پذیرایی", "صبحانه", "ناهار", "شام", "بسته پذیرایی")):
            star_hints["reception"] = 1
        if any(w in combined for w in ("پوستر", "اطلاعیه", "بنر", "اطلاع‌رسانی", "فضای مجازی")):
            star_hints["announcement"] = 1
        if any(w in combined for w in ("سخنرانی", "سخنران", "مداح", "مداحی", "حجت‌الاسلام")):
            star_hints["speaker_coordination"] = 1
        if any(w in combined for w in ("اهدای جوایز", "هدایا", "تقدیرنامه", "لوح تقدیر", "بسته فرهنگی")):
            star_hints["gifts"] = 1
            star_hints["culture_pack"] = 1

        provenance = {
            "candidate_id": candidate_id,
            "rule_name": rule_name,
            "rule_version": self.RULE_VERSION,
            "matched_programs": list(matched_programs),
            "text_length": len(content),
            "is_ashura": is_ashura,
            "official_present": official_present,
            "is_abstain": is_abstain,
        }

        return AgentSuggestion(
            candidate_id=candidate_id,
            recommended_program=recommended_prog,
            confidence=confidence,
            reasoning="؛ ".join(reasons) if reasons else "تحلیل متنی خودکار انجام شد.",
            extracted_attendees=extracted_attendees,
            extracted_unit_scope=extracted_unit_scope,
            extracted_unit_name=extracted_unit_name,
            official_present_suggested=official_present,
            is_ashura_pilgrimage=is_ashura,
            star_field_hints=star_hints,
            rule_version=self.RULE_VERSION,
            rule_name=rule_name,
            provenance=provenance,
            is_abstain=is_abstain,
        )
