"""Coordinator persistence and safe legacy-migration primitives."""

from .app_auth import (
    AppAuthPolicy,
    AppPrincipal,
    AuthorizedAppSession,
    CoordinatorAppAuth,
    FileKeySubjectFingerprinter,
    IssuedAppSession,
    PasswordHasher,
    StaticSubjectFingerprinter,
    WindowsDpapiSubjectFingerprinter,
    normalize_username,
    validate_display_name,
)
from .audit import (
    AuditExportResult,
    AuditPage,
    AuditVerificationReport,
    SafeAuditEvent,
    SafeCoordinatorAuditService,
)
from .identity import (
    FileKeyPhoneProtector,
    PhoneProtector,
    ProtectedPhone,
    WindowsDpapiPhoneProtector,
    default_phone_protector,
    masked_phone,
    validate_canonical_e164,
)
from .jobs import (
    CreateJobResult,
    JobAttemptRecord,
    JobLeaseRecord,
    JobRecoverySummary,
    OperationJobRecord,
    PersistentOperationJobService,
)
from .migration import (
    LegacyMigrationService,
    LegacyPreflightReport,
    MigrationResult,
    PreflightCheck,
)
from .rate_policy import (
    AccountExecutionPolicyService,
    ClassifiedFailure,
    ExecutionErrorClass,
    ExecutionPermit,
    FailureDecision,
    classify_failure,
)
from .schema import COORDINATOR_SCHEMA_VERSION
from .store import (
    AppIntegrationRecord,
    CoordinatorDatabase,
    LegacyBootstrapResult,
    MessengerAccountPhoneIdentity,
    MessengerAccountOnboardingResult,
    MessengerAccountRuntimeRecord,
    ProviderRegistrationRecord,
    WorkerInstanceRecord,
    WorkerRecoveryDecision,
)
from .receipts import (
    ProviderOperationClaim,
    ProviderOperationReceiptRecord,
    ProviderOperationReceiptStore,
)

__all__ = [
    "AccountExecutionPolicyService",
    "AppIntegrationRecord",
    "AppAuthPolicy",
    "AppPrincipal",
    "AuditExportResult",
    "AuditPage",
    "AuditVerificationReport",
    "AuthorizedAppSession",
    "COORDINATOR_SCHEMA_VERSION",
    "CoordinatorAppAuth",
    "CoordinatorDatabase",
    "ClassifiedFailure",
    "CreateJobResult",
    "ExecutionErrorClass",
    "ExecutionPermit",
    "FailureDecision",
    "FileKeyPhoneProtector",
    "FileKeySubjectFingerprinter",
    "IssuedAppSession",
    "JobAttemptRecord",
    "JobLeaseRecord",
    "JobRecoverySummary",
    "LegacyBootstrapResult",
    "MessengerAccountPhoneIdentity",
    "MessengerAccountOnboardingResult",
    "MessengerAccountRuntimeRecord",
    "ProviderRegistrationRecord",
    "ProviderOperationClaim",
    "ProviderOperationReceiptRecord",
    "ProviderOperationReceiptStore",
    "OperationJobRecord",
    "PersistentOperationJobService",
    "WorkerInstanceRecord",
    "WorkerRecoveryDecision",
    "LegacyMigrationService",
    "LegacyPreflightReport",
    "MigrationResult",
    "PreflightCheck",
    "PasswordHasher",
    "PhoneProtector",
    "ProtectedPhone",
    "SafeAuditEvent",
    "SafeCoordinatorAuditService",
    "StaticSubjectFingerprinter",
    "WindowsDpapiPhoneProtector",
    "WindowsDpapiSubjectFingerprinter",
    "default_phone_protector",
    "masked_phone",
    "normalize_username",
    "validate_display_name",
    "validate_canonical_e164",
    "classify_failure",
]
